# Generated by Django 4.0.2 on 2024-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=100)),
                ('date_construction', models.IntegerField(blank=True, default=2024, null=True)),
                ('plus_floor', models.IntegerField(blank=True, default=0, null=True)),
                ('minus_floor', models.IntegerField(blank=True, default=0, null=True)),
                ('units', models.IntegerField(blank=True, default=0, null=True)),
                ('units_in_floor', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_meterage', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
