# Generated by Django 4.0.2 on 2024-06-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectphotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectPhotos',
            new_name='ProjectPhoto',
        ),
    ]
