# Generated by Django 5.0.6 on 2024-06-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_projectphotos_projectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
