# Generated by Django 5.0.6 on 2024-06-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_image_project_image_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Done', 'Done!'), ('building', 'Building...')], default=1, max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
