# Generated by Django 5.0.6 on 2024-06-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ground_meterage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='meterage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='plus_floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='floors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('done', 'Done!'), ('building', 'Building...')], max_length=20, verbose_name='Status'),
        ),
    ]
