# Generated by Django 5.0.6 on 2024-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_ground_meterage_alter_project_plus_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='room',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ground_meterage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ground meterage'),
        ),
    ]
