# Generated by Django 5.0.6 on 2024-07-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_room_alter_project_ground_meterage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_construction',
        ),
    ]
