# Generated by Django 5.0.6 on 2024-07-06 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_room_alter_project_ground_meterage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_construction',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 7, 6, 22, 53, 37, 143473, tzinfo=datetime.timezone.utc), null=True, verbose_name='date construction'),
        ),
    ]
