# Generated by Django 5.0.6 on 2024-07-06 22:58

import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_date_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_construction',
            field=models.DateField(default=jdatetime.datetime.date, verbose_name='date construction'),
        ),
    ]
