# Generated by Django 5.0.6 on 2024-07-06 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_date_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='built_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date construction'),
        ),
    ]
