# Generated by Django 5.0.6 on 2024-07-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_built_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='built_date',
        ),
    ]
