# Generated by Django 5.0.6 on 2024-07-06 22:50

import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_project_built_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='built_date',
            field=models.DateField(default=jdatetime.datetime.date, verbose_name='date construction'),
        ),
    ]
