# Generated by Django 5.0.6 on 2024-07-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_date_construction'),
        ('projects', '0012_project_date_construction'),
        ('projects', '0016_project_built_date'),
    ]

    operations = [
    ]
