# Generated by Django 5.0.6 on 2024-07-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_merge_20240708_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='built_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='room',
        ),
        migrations.RemoveField(
            model_name='project',
            name='unit_meterage',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_construction',
            field=models.IntegerField(blank=True, default=2024, null=True, verbose_name='date construction'),
        ),
    ]
