# Generated by Django 5.0.6 on 2024-07-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('image', models.ImageField(upload_to='Brand_materials/brand_cover/', verbose_name='Brand Image')),
            ],
        ),
    ]
